### PR TITLE
Error fixes

### PR DESCRIPTION
**Pull request by itthought**
Updated tsconfig.json for removing error
(node_modules/@theia/plugin/src/theia.d.ts(4733,29): error TS2304:
Cannot find name 'Thenable'.)

Reference: https://github.com/eclipse-theia/theia/issues/3262

### CODE REVIEW

**Comment by benoitf** [comment]
@itthought you need to sign the Eclipse ECA so I could merge your pR

**Comment by vitaliy-guliy** [comment]
the changes introduced by https://github.com/eclipse/theia-generator-plugin/pull/36
